In [2]:
import numpy as np

a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [10]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()
print(c)
print(f"vectorized version: {str(1000*(toc-tic))}ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i] * b[i]
toc = time.time()

print(c)
print(f"for loop: {str(1000*(toc-tic))}ms")

249603.00495730859
vectorized version: 0.5297660827636719ms
249603.00495730597
for loop: 192.68488883972168ms


# Python numpy stuff

In [22]:
a = np.random.randn(4, 3)
b = np.random.randn(3, 2)

c = a * b
c.shape

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [26]:
a = np.array([[1, 1], [1, -1]])
a = np.array([[2], [3]])

c = a + b
c

ValueError: operands could not be broadcast together with shapes (2,1) (3,2) 

In [ ]:
import numpy as np

# wrong
a = np.random.randn(5)
print(a)
print(a.shape)
print(a.T)
print(np.dot(a, a.T))

[-0.9119534  -1.31158034 -1.03428988 -0.34371838  1.69393786]
(5,)
[-0.9119534  -1.31158034 -1.03428988 -0.34371838  1.69393786]
6.609225349578894


In [7]:
a = np.random.randn(5, 1)
print(a)
print(a.T)

[[-0.70139662]
 [-0.10208201]
 [ 0.58000019]
 [-0.53137657]
 [ 1.15337983]]
[[-0.70139662 -0.10208201  0.58000019 -0.53137657  1.15337983]]
